# ----------------------------------------------------------------------------
# A dataset of fruit category and fruit data for use in examples.
#
# Data from http://www.fda.gov/Food/LabelingNutrition/\
#                FoodLabelingGuidanceRegulatoryInformation/\
#                InformationforRestaurantsRetailEstablishments/\
#                ucm063482.htm
#
# Available items for import are:
#
#     fruit_categories
#     fruit_data_attributes
#     fruit_data_attribute_units
#     fruit_data_list_of_dicts
#     fruit_data
#

#import pprint

fruit_categories = \
        {'Melons': {'name': 'Melons',
                    'fruits': ['Cantaloupe', 'Honeydew', 'Watermelon'],
                    'is_selected': False},
         'Tree Fruits': {'name': 'Tree Fruits',
                         'fruits': ['Apple', 'Avocado', 'Banana', 'Nectarine',
                                    'Peach', 'Pear', 'Pineapple', 'Plum',
                                    'Cherry'],
                         'is_selected': False},
         'Citrus Fruits': {'name': 'Citrus Fruits',
                           'fruits': ['Grapefruit', 'Lemon', 'Lime', 'Orange',
                                      'Tangerine'],
                           'is_selected': False},
         'Other Fruits': {'name': 'Other Fruits',
                          'fruits': ['Grape', 'Kiwifruit',
                                     'Strawberry'],
                          'is_selected': False}}

fruit_data_list_of_dicts = [
{'name':'Apple',
 'Serving Size': '1 large (242 g/8 oz)',
 'data': [130, 0, 0, 0, 0, 0, 260, 7, 34, 11, 5, 20, 25, 1, 2, 8, 2, 2],
 'is_selected': False},
{'name':'Avocado',
 'Serving Size': '1/5 medium (30 g/1.1 oz)',
 'data': [50, 35, 4.5, 7, 0, 0, 140, 4, 3, 1, 1, 4, 0, 1, 0, 4, 0, 2],
 'is_selected': False},
{'name':'Banana',
 'Serving Size': '1 medium (126 g/4.5 oz)',
 'data': [110, 0, 0, 0, 0, 0, 450, 13, 30, 10, 3, 12, 19, 1, 2, 15, 0, 2],
 'is_selected': False},
{'name':'Cantaloupe',
 'Serving Size': '1/4 medium (134 g/4.8 oz)',
 'data': [50, 0, 0, 0, 20, 1, 240, 7, 12, 4, 1, 4, 11, 1, 120, 80, 2, 2],
 'is_selected': False},
{'name':'Grapefruit',
 'Serving Size': '1/2 medium (154 g/5.5 oz)',
 'data': [60, 0, 0, 0, 0, 0, 160, 5, 15, 5, 2, 8, 11, 1, 35, 100, 4, 0],
 'is_selected': False},
{'name':'Grape',
 'Serving Size': '3/4 cup (126 g/4.5 oz)',
 'data': [90, 0, 0, 0, 15, 1, 240, 7, 23, 8, 1, 4, 20, 0, 0, 2, 2, 0],
 'is_selected': False},
{'name':'Honeydew',
 'Serving Size': '1/10 medium melon (134 g/4.8 oz)',
 'data': [50, 0, 0, 0, 30, 1, 210, 6, 12, 4, 1, 4, 11, 1, 2, 45, 2, 2],
 'is_selected': False},
{'name':'Kiwifruit',
 'Serving Size': '2 medium (148 g/5.3 oz)',
 'data': [90, 10, 1, 2, 0, 0, 450, 13, 20, 7, 4, 16, 13, 1, 2, 240, 4, 2],
 'is_selected': False},
{'name':'Lemon',
 'Serving Size': '1 medium (58 g/2.1 oz)',
 'data': [15, 0, 0, 0, 0, 0, 75, 2, 5, 2, 2, 8, 2, 0, 0, 40, 2, 0],
 'is_selected': False},
{'name':'Lime',
 'Serving Size': '1 medium (67 g/2.4 oz)',
 'data': [20, 0, 0, 0, 0, 0, 75, 2, 7, 2, 2, 8, 0, 0, 0, 35, 0, 0],
 'is_selected': False},
{'name':'Nectarine',
 'Serving Size': '1 medium (140 g/5.0 oz)',
 'data': [60, 5, 0.5, 1, 0, 0, 250, 7, 15, 5, 2, 8, 11, 1, 8, 15, 0, 2],
 'is_selected': False},
{'name':'Orange',
 'Serving Size': '1 medium (154 g/5.5 oz)',
 'data': [80, 0, 0, 0, 0, 0, 250, 7, 19, 6, 3, 12, 14, 1, 2, 130, 6, 0],
 'is_selected': False},
{'name':'Peach',
 'Serving Size': '1 medium (147 g/5.3 oz)',
 'data': [60, 0, 0.5, 1, 0, 0, 230, 7, 15, 5, 2, 8, 13, 1, 6, 15, 0, 2],
 'is_selected': False},
{'name':'Pear',
 'Serving Size': '1 medium (166 g/5.9 oz)',
 'data': [100, 0, 0, 0, 0, 0, 190, 5, 26, 9, 6, 24, 16, 1, 0, 10, 2, 0],
 'is_selected': False},
{'name':'Pineapple',
 'Serving Size': '2 slices, 3" diameter, 3/4" thick (112 g/4 oz)',
 'data': [50, 0, 0, 0, 10, 0, 120, 3, 13, 4, 1, 4, 10, 1, 2, 50, 2, 2],
 'is_selected': False},
{'name':'Plum',
 'Serving Size': '2 medium (151 g/5.4 oz)',
 'data': [70, 0, 0, 0, 0, 0, 230, 7, 19, 6, 2, 8, 16, 1, 8, 10, 0, 2],
 'is_selected': False},
{'name':'Strawberry',
 'Serving Size': '8 medium (147 g/5.3 oz)',
 'data': [50, 0, 0, 0, 0, 0, 170, 5, 11, 4, 2, 8, 8, 1, 0, 160, 2, 2],
 'is_selected': False},
{'name':'Cherry',
 'Serving Size': '21 cherries; 1 cup (140 g/5.0 oz)',
 'data': [100, 0, 0, 0, 0, 0, 350, 10, 26, 9, 1, 4, 16, 1, 2, 15, 2, 2],
 'is_selected': False},
{'name':'Tangerine',
 'Serving Size': '1 medium (109 g/3.9 oz)',
 'data': [50, 0, 0, 0, 0, 0, 160, 5, 13, 4, 2, 8, 9, 1, 6, 45, 4, 0],
 'is_selected': False},
{'name':'Watermelon',
 'Serving Size': '1/18 medium melon; 2 cups diced pieces (280 g/10.0 oz)',
 'data': [80, 0, 0, 0, 0, 0, 270, 8, 21, 7, 1, 4, 20, 1, 30, 25, 2, 4],
 'is_selected': False}]

fruit_data_names_and_attributes = \
        [('calories', 'Calories'),
         ('calories_from_fat', 'Calories from Fat'),
         ('total_fat_g', 'Total Fat (g)'),
         ('total_fat_dv', 'Total Fat (%DV)'),
         ('sodium_mg', 'Sodium (mg)'),
         ('sodium_dv', 'Sodium (%DV)'),
         ('potassium_mg', 'Potassium (mg)'),
         ('potassium_dv', 'Potassium (%DV)'),
         ('total_carbohydrate_g', 'Total Carbohydrate (g)'),
         ('total_carbohydrate_dv', 'Total Carbohydrate (%DV)'),
         ('dietary_fiber_g', 'Dietary Fiber (g)'),
         ('dietary_fiber_dv', 'Dietary Fiber (%DV)'),
         ('sugars_g', 'Sugars (g)'),
         ('protein_g', 'Protein (g)'),
         ('vitamin_a_dv', 'Vitamin A (%DV)'),
         ('vitamin_c_dv', 'Vitamin C (%DV)'),
         ('calcium_dv', 'Calcium (%DV)'),
         ('iron_dv', 'Iron (%DV)')]

fruit_data_names, fruit_data_attributes = zip(*fruit_data_names_and_attributes)

# fruit_data generated with the following:
#
#fruit_data = {}
#for fruit_record in fruit_data_list_of_dicts:
#    fruit_data[fruit_record['name']] = {}
#    fruit_data[fruit_record['name']] = \
#            dict({'Serving Size': fruit_record['Serving Size'],
#                  'is_selected': fruit_record['is_selected']},
#            **dict(zip(fruit_data_names, fruit_record['data'])))
#
#pp = pprint.PrettyPrinter(indent=4)
#pp.pprint(fruit_data)

fruit_data = \
{   'Apple': {   'Serving Size': '1 large (242 g/8 oz)',
                 'calcium_dv': 2,
                 'calories': 130,
                 'calories_from_fat': 0,
                 'dietary_fiber_dv': 20,
                 'dietary_fiber_g': 5,
                 'iron_dv': 2,
                 'is_selected': False,
                 'potassium_dv': 7,
                 'potassium_mg': 260,
                 'protein_g': 1,
                 'sodium_dv': 0,
                 'sodium_mg': 0,
                 'sugars_g': 25,
                 'total_carbohydrate_dv': 11,
                 'total_carbohydrate_g': 34,
                 'total_fat_dv': 0,
                 'total_fat_g': 0,
                 'vitamin_a_dv': 2,
                 'vitamin_c_dv': 8},
    'Avocado': {   'Serving Size': '1/5 medium (30 g/1.1 oz)',
                   'calcium_dv': 0,
                   'calories': 50,
                   'calories_from_fat': 35,
                   'dietary_fiber_dv': 4,
                   'dietary_fiber_g': 1,
                   'iron_dv': 2,
                   'is_selected': False,
                   'potassium_dv': 4,
                   'potassium_mg': 140,
                   'protein_g': 1,
                   'sodium_dv': 0,
                   'sodium_mg': 0,
                   'sugars_g': 0,
                   'total_carbohydrate_dv': 1,
                   'total_carbohydrate_g': 3,
                   'total_fat_dv': 7,
                   'total_fat_g': 4.5,
                   'vitamin_a_dv': 0,
                   'vitamin_c_dv': 4},
    'Banana': {   'Serving Size': '1 medium (126 g/4.5 oz)',
                  'calcium_dv': 0,
                  'calories': 110,
                  'calories_from_fat': 0,
                  'dietary_fiber_dv': 12,
                  'dietary_fiber_g': 3,
                  'iron_dv': 2,
                  'is_selected': False,
                  'potassium_dv': 13,
                  'potassium_mg': 450,
                  'protein_g': 1,
                  'sodium_dv': 0,
                  'sodium_mg': 0,
                  'sugars_g': 19,
                  'total_carbohydrate_dv': 10,
                  'total_carbohydrate_g': 30,
                  'total_fat_dv': 0,
                  'total_fat_g': 0,
                  'vitamin_a_dv': 2,
                  'vitamin_c_dv': 15},
    'Cantaloupe': {   'Serving Size': '1/4 medium (134 g/4.8 oz)',
                      'calcium_dv': 2,
                      'calories': 50,
                      'calories_from_fat': 0,
                      'dietary_fiber_dv': 4,
                      'dietary_fiber_g': 1,
                      'iron_dv': 2,
                      'is_selected': False,
                      'potassium_dv': 7,
                      'potassium_mg': 240,
                      'protein_g': 1,
                      'sodium_dv': 1,
                      'sodium_mg': 20,
                      'sugars_g': 11,
                      'total_carbohydrate_dv': 4,
                      'total_carbohydrate_g': 12,
                      'total_fat_dv': 0,
                      'total_fat_g': 0,
                      'vitamin_a_dv': 120,
                      'vitamin_c_dv': 80},
    'Cherry': {   'Serving Size': '21 cherries; 1 cup (140 g/5.0 oz)',
                  'calcium_dv': 2,
                  'calories': 100,
                  'calories_from_fat': 0,
                  'dietary_fiber_dv': 4,
                  'dietary_fiber_g': 1,
                  'iron_dv': 2,
                  'is_selected': False,
                  'potassium_dv': 10,
                  'potassium_mg': 350,
                  'protein_g': 1,
                  'sodium_dv': 0,
                  'sodium_mg': 0,
                  'sugars_g': 16,
                  'total_carbohydrate_dv': 9,
                  'total_carbohydrate_g': 26,
                  'total_fat_dv': 0,
                  'total_fat_g': 0,
                  'vitamin_a_dv': 2,
                  'vitamin_c_dv': 15},
    'Grape': {   'Serving Size': '3/4 cup (126 g/4.5 oz)',
                 'calcium_dv': 2,
                 'calories': 90,
                 'calories_from_fat': 0,
                 'dietary_fiber_dv': 4,
                 'dietary_fiber_g': 1,
                 'iron_dv': 0,
                 'is_selected': False,
                 'potassium_dv': 7,
                 'potassium_mg': 240,
                 'protein_g': 0,
                 'sodium_dv': 1,
                 'sodium_mg': 15,
                 'sugars_g': 20,
                 'total_carbohydrate_dv': 8,
                 'total_carbohydrate_g': 23,
                 'total_fat_dv': 0,
                 'total_fat_g': 0,
                 'vitamin_a_dv': 0,
                 'vitamin_c_dv': 2},
    'Grapefruit': {   'Serving Size': '1/2 medium (154 g/5.5 oz)',
                      'calcium_dv': 4,
                      'calories': 60,
                      'calories_from_fat': 0,
                      'dietary_fiber_dv': 8,
                      'dietary_fiber_g': 2,
                      'iron_dv': 0,
                      'is_selected': False,
                      'potassium_dv': 5,
                      'potassium_mg': 160,
                      'protein_g': 1,
                      'sodium_dv': 0,
                      'sodium_mg': 0,
                      'sugars_g': 11,
                      'total_carbohydrate_dv': 5,
                      'total_carbohydrate_g': 15,
                      'total_fat_dv': 0,
                      'total_fat_g': 0,
                      'vitamin_a_dv': 35,
                      'vitamin_c_dv': 100},
    'Honeydew': {   'Serving Size': '1/10 medium melon (134 g/4.8 oz)',
                    'calcium_dv': 2,
                    'calories': 50,
                    'calories_from_fat': 0,
                    'dietary_fiber_dv': 4,
                    'dietary_fiber_g': 1,
                    'iron_dv': 2,
                    'is_selected': False,
                    'potassium_dv': 6,
                    'potassium_mg': 210,
                    'protein_g': 1,
                    'sodium_dv': 1,
                    'sodium_mg': 30,
                    'sugars_g': 11,
                    'total_carbohydrate_dv': 4,
                    'total_carbohydrate_g': 12,
                    'total_fat_dv': 0,
                    'total_fat_g': 0,
                    'vitamin_a_dv': 2,
                    'vitamin_c_dv': 45},
    'Kiwifruit': {   'Serving Size': '2 medium (148 g/5.3 oz)',
                     'calcium_dv': 4,
                     'calories': 90,
                     'calories_from_fat': 10,
                     'dietary_fiber_dv': 16,
                     'dietary_fiber_g': 4,
                     'iron_dv': 2,
                     'is_selected': False,
                     'potassium_dv': 13,
                     'potassium_mg': 450,
                     'protein_g': 1,
                     'sodium_dv': 0,
                     'sodium_mg': 0,
                     'sugars_g': 13,
                     'total_carbohydrate_dv': 7,
                     'total_carbohydrate_g': 20,
                     'total_fat_dv': 2,
                     'total_fat_g': 1,
                     'vitamin_a_dv': 2,
                     'vitamin_c_dv': 240},
    'Lemon': {   'Serving Size': '1 medium (58 g/2.1 oz)',
                 'calcium_dv': 2,
                 'calories': 15,
                 'calories_from_fat': 0,
                 'dietary_fiber_dv': 8,
                 'dietary_fiber_g': 2,
                 'iron_dv': 0,
                 'is_selected': False,
                 'potassium_dv': 2,
                 'potassium_mg': 75,
                 'protein_g': 0,
                 'sodium_dv': 0,
                 'sodium_mg': 0,
                 'sugars_g': 2,
                 'total_carbohydrate_dv': 2,
                 'total_carbohydrate_g': 5,
                 'total_fat_dv': 0,
                 'total_fat_g': 0,
                 'vitamin_a_dv': 0,
                 'vitamin_c_dv': 40},
    'Lime': {   'Serving Size': '1 medium (67 g/2.4 oz)',
                'calcium_dv': 0,
                'calories': 20,
                'calories_from_fat': 0,
                'dietary_fiber_dv': 8,
                'dietary_fiber_g': 2,
                'iron_dv': 0,
                'is_selected': False,
                'potassium_dv': 2,
                'potassium_mg': 75,
                'protein_g': 0,
                'sodium_dv': 0,
                'sodium_mg': 0,
                'sugars_g': 0,
                'total_carbohydrate_dv': 2,
                'total_carbohydrate_g': 7,
                'total_fat_dv': 0,
                'total_fat_g': 0,
                'vitamin_a_dv': 0,
                'vitamin_c_dv': 35},
    'Nectarine': {   'Serving Size': '1 medium (140 g/5.0 oz)',
                     'calcium_dv': 0,
                     'calories': 60,
                     'calories_from_fat': 5,
                     'dietary_fiber_dv': 8,
                     'dietary_fiber_g': 2,
                     'iron_dv': 2,
                     'is_selected': False,
                     'potassium_dv': 7,
                     'potassium_mg': 250,
                     'protein_g': 1,
                     'sodium_dv': 0,
                     'sodium_mg': 0,
                     'sugars_g': 11,
                     'total_carbohydrate_dv': 5,
                     'total_carbohydrate_g': 15,
                     'total_fat_dv': 1,
                     'total_fat_g': 0.5,
                     'vitamin_a_dv': 8,
                     'vitamin_c_dv': 15},
    'Orange': {   'Serving Size': '1 medium (154 g/5.5 oz)',
                  'calcium_dv': 6,
                  'calories': 80,
                  'calories_from_fat': 0,
                  'dietary_fiber_dv': 12,
                  'dietary_fiber_g': 3,
                  'iron_dv': 0,
                  'is_selected': False,
                  'potassium_dv': 7,
                  'potassium_mg': 250,
                  'protein_g': 1,
                  'sodium_dv': 0,
                  'sodium_mg': 0,
                  'sugars_g': 14,
                  'total_carbohydrate_dv': 6,
                  'total_carbohydrate_g': 19,
                  'total_fat_dv': 0,
                  'total_fat_g': 0,
                  'vitamin_a_dv': 2,
                  'vitamin_c_dv': 130},
    'Peach': {   'Serving Size': '1 medium (147 g/5.3 oz)',
                 'calcium_dv': 0,
                 'calories': 60,
                 'calories_from_fat': 0,
                 'dietary_fiber_dv': 8,
                 'dietary_fiber_g': 2,
                 'iron_dv': 2,
                 'is_selected': False,
                 'potassium_dv': 7,
                 'potassium_mg': 230,
                 'protein_g': 1,
                 'sodium_dv': 0,
                 'sodium_mg': 0,
                 'sugars_g': 13,
                 'total_carbohydrate_dv': 5,
                 'total_carbohydrate_g': 15,
                 'total_fat_dv': 1,
                 'total_fat_g': 0.5,
                 'vitamin_a_dv': 6,
                 'vitamin_c_dv': 15},
    'Pear': {   'Serving Size': '1 medium (166 g/5.9 oz)',
                'calcium_dv': 2,
                'calories': 100,
                'calories_from_fat': 0,
                'dietary_fiber_dv': 24,
                'dietary_fiber_g': 6,
                'iron_dv': 0,
                'is_selected': False,
                'potassium_dv': 5,
                'potassium_mg': 190,
                'protein_g': 1,
                'sodium_dv': 0,
                'sodium_mg': 0,
                'sugars_g': 16,
                'total_carbohydrate_dv': 9,
                'total_carbohydrate_g': 26,
                'total_fat_dv': 0,
                'total_fat_g': 0,
                'vitamin_a_dv': 0,
                'vitamin_c_dv': 10},
    'Pineapple': {   'Serving Size': '2 slices, 3" diameter, 3/4" thick (112 g/4 oz)',
                     'calcium_dv': 2,
                     'calories': 50,
                     'calories_from_fat': 0,
                     'dietary_fiber_dv': 4,
                     'dietary_fiber_g': 1,
                     'iron_dv': 2,
                     'is_selected': False,
                     'potassium_dv': 3,
                     'potassium_mg': 120,
                     'protein_g': 1,
                     'sodium_dv': 0,
                     'sodium_mg': 10,
                     'sugars_g': 10,
                     'total_carbohydrate_dv': 4,
                     'total_carbohydrate_g': 13,
                     'total_fat_dv': 0,
                     'total_fat_g': 0,
                     'vitamin_a_dv': 2,
                     'vitamin_c_dv': 50},
    'Plum': {   'Serving Size': '2 medium (151 g/5.4 oz)',
                'calcium_dv': 0,
                'calories': 70,
                'calories_from_fat': 0,
                'dietary_fiber_dv': 8,
                'dietary_fiber_g': 2,
                'iron_dv': 2,
                'is_selected': False,
                'potassium_dv': 7,
                'potassium_mg': 230,
                'protein_g': 1,
                'sodium_dv': 0,
                'sodium_mg': 0,
                'sugars_g': 16,
                'total_carbohydrate_dv': 6,
                'total_carbohydrate_g': 19,
                'total_fat_dv': 0,
                'total_fat_g': 0,
                'vitamin_a_dv': 8,
                'vitamin_c_dv': 10},
    'Strawberry': {   'Serving Size': '8 medium (147 g/5.3 oz)',
                      'calcium_dv': 2,
                      'calories': 50,
                      'calories_from_fat': 0,
                      'dietary_fiber_dv': 8,
                      'dietary_fiber_g': 2,
                      'iron_dv': 2,
                      'is_selected': False,
                      'potassium_dv': 5,
                      'potassium_mg': 170,
                      'protein_g': 1,
                      'sodium_dv': 0,
                      'sodium_mg': 0,
                      'sugars_g': 8,
                      'total_carbohydrate_dv': 4,
                      'total_carbohydrate_g': 11,
                      'total_fat_dv': 0,
                      'total_fat_g': 0,
                      'vitamin_a_dv': 0,
                      'vitamin_c_dv': 160},
    'Tangerine': {   'Serving Size': '1 medium (109 g/3.9 oz)',
                     'calcium_dv': 4,
                     'calories': 50,
                     'calories_from_fat': 0,
                     'dietary_fiber_dv': 8,
                     'dietary_fiber_g': 2,
                     'iron_dv': 0,
                     'is_selected': False,
                     'potassium_dv': 5,
                     'potassium_mg': 160,
                     'protein_g': 1,
                     'sodium_dv': 0,
                     'sodium_mg': 0,
                     'sugars_g': 9,
                     'total_carbohydrate_dv': 4,
                     'total_carbohydrate_g': 13,
                     'total_fat_dv': 0,
                     'total_fat_g': 0,
                     'vitamin_a_dv': 6,
                     'vitamin_c_dv': 45},
    'Watermelon': {   'Serving Size': '1/18 medium melon; 2 cups diced pieces (280 g/10.0 oz)',
                      'calcium_dv': 2,
                      'calories': 80,
                      'calories_from_fat': 0,
                      'dietary_fiber_dv': 4,
                      'dietary_fiber_g': 1,
                      'iron_dv': 4,
                      'is_selected': False,
                      'potassium_dv': 8,
                      'potassium_mg': 270,
                      'protein_g': 1,
                      'sodium_dv': 0,
                      'sodium_mg': 0,
                      'sugars_g': 20,
                      'total_carbohydrate_dv': 7,
                      'total_carbohydrate_g': 21,
                      'total_fat_dv': 0,
                      'total_fat_g': 0,
                      'vitamin_a_dv': 30,
                      'vitamin_c_dv': 25}}
